### ISSUE TITLE
Have you tried to deploy this?

### ISSUE THREAD

**Issue by albingroen** [mikenikles/sveltekit-prisma#1]
Hey, I have a setup like this, but when I deploy to Vercel I receive this screen.

![image](https://user-images.githubusercontent.com/19674362/134782664-bce50bf8-a8ef-48c9-b22f-09356ef127ab.png)

If I remove anything related to Prisma in my endpoint, and just return a empty array, it works.

Would love to hear if you've experienced anything similar?

**Comment by mikenikles** [comment]
Hi Albin, I got it to a point where it builds & deploys, but I can't load the todos because the local sqlite `./dev.db` file can't be opened. This is most likely due to how Vercel's local file system works and the fact that `./dev.db` is not available at runtime. A good starting point to dive deeper is https://vercel.com/docs/runtimes#advanced-usage/technical-details/including-additional-files.

A few changes were needed to get it to deploy on Vercel:
- 5b9d199 - Ensure PrismaClient gets generated on Vercel.
- 90e9124 - ESM & CommonJS support
- 68b6366 - Specify the native binary target
- 626a61e - Add a postbuild npm script to copy the query engines.

Having said that, if you change the `.prisma/schema.prisma` to point the data source to an external database, it may work on Vercel ([see docs](https://www.prisma.io/docs/concepts/components/prisma-schema/data-sources/)):

```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}
```

Please keep me posted.

PS: If you click "check the logs" in your error message, what additional details do you see? That may help us narrow down what's going on.

**Comment by albingroen** [comment]
I'm using a Postgres database from Heroku, so that shouldn't be the issue.

I have now made all the changes you listed above in the commit list, except this one

https://github.com/mikenikles/sveltekit-prisma/commit/626a61eb04ef11d5b9ab353e11d1ff3def0d5b3f

Because, I don't seem to have a `query-engine` file inside of `node_modules/@prisma/engines`

**Comment by albingroen** [comment]
Ah okay, I had to change it to

```
"postbuild": "cp node_modules/@prisma/engines/libquery_engine-* .vercel_build_output/functions/node/render/;cp prisma/schema.prisma .vercel_build_output/functions/node/render/"
```

Then it worked.

**Comment by mikenikles** [comment]
Alright, maybe because you use a different DB 🤷.

Awesome, glad to hear it works. That was a fun little exercise ☺️.
