### ISSUE TITLE
The todo example throws a 500 Error

### ISSUE THREAD

**Issue by jonbitgood** [mikenikles/sveltekit-prisma#5]
Both the online example and my local copy of the project throw a `Unexpected token E in JSON at position 0` error.

[https://sveltekit-prisma.vercel.app/todos](https://sveltekit-prisma.vercel.app/todos)

**Comment by mikenikles** [comment]
Hi Jon, let me address local vs online separately.

**Vercel**
The Vercel deployment throws that error because I use sqlite which uses the local file system, but that fails on Vercel. If you configure an external database in the `prisma/schema.prisma` file, you should be ok on Vercel.

**Local**
What operating system do you use? I wonder if there may be something up with compiling the Prisma client. I use Gitpod as my development environment and it works there, which uses Ubuntu. Curious to get to the bottom of that in your case.

**Comment by jonbitgood** [comment]
Using macOS Big Sur with a mysql 8 database. I'm going to try a couple different database drivers for prisma and see if the error is universal or just on certain database types.

**Comment by jonbitgood** [comment]
This was actually related to the version of sveltekit. Updating to fix [the exports issue](https://github.com/sveltejs/kit/issues/2384) solved it.
